/// <reference lib="webworker" />
import { precacheAndRoute } from 'workbox-precaching'

// Service workers run in ServiceWorkerGlobalScope, not Window
declare let self: ServiceWorkerGlobalScope

// Precache static assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST)

// Listen for push notifications
self.addEventListener('push', (event: PushEvent) => {
  let data = { title: 'HydroTrack', body: 'Time to drink water!', url: '/' }
  if (event.data) {
    try {
      data = event.data.json()
    } catch {
      data.body = event.data.text()
    }
  }

  const options = {
    body: data.body,
    icon: '/icon-192.png',
    badge: '/icon-192.png',
    data: {
      url: data.url || '/'
    }
  }

  event.waitUntil(
    self.registration.showNotification(data.title, options)
  )
})

// Handle notification click
self.addEventListener('notificationclick', (event: NotificationEvent) => {
  event.notification.close()
  
  // Open the target URL or focus existing window
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList: readonly WindowClient[]) => {
      const urlToOpen = new URL(event.notification.data.url, self.location.origin).href
      for (const client of clientList) {
        if (client.url === urlToOpen && 'focus' in client) {
          return client.focus()
        }
      }
      if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen)
      }
    })
  )
})

